/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iiitb.gui;

import com.iiitb.config.LOMSProperties;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author ARUN
 */
public class ConfigPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConfigPanel
     */
    public ConfigPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configDirChooser = new javax.swing.JFileChooser();
        tempLocationField = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();
        locationLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();

        configDirChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP));

        tempLocationField.setEditable(false);
        com.iiitb.config.LOMSProperties prop = new com.iiitb.config.LOMSProperties();
        tempLocationField.setText(prop.getTempDirectory());

        changeButton.setText("Change...");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        locationLabel.setText("Temporary Package Location");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempLocationField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeButton))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationLabel)
                    .addComponent(saveButton))
                .addGap(0, 254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(locationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        configDirChooser.setFileView(null);
        int returnVal = configDirChooser.showDialog(this, "Select Directory");

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            final File selectedFile = configDirChooser.getSelectedFile();
            tempLocationField.setText(selectedFile.toString());
            System.out.println("Directory::" + selectedFile.toString());


        } else {
            System.out.println("File access cancelled by user");
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        LOMSProperties lomProp = new LOMSProperties();
        lomProp.setTempDirectory(tempLocationField.getText());
    }//GEN-LAST:event_saveButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JFileChooser configDirChooser;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField tempLocationField;
    // End of variables declaration//GEN-END:variables
}
