package com.iiitb.gui;

import com.iiitb.utils.RepositoryManager;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;

/**
 *
 * @author ARUN
 */
public class RepositoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form RepositoryPanel
     */
    public RepositoryPanel() {
        initComponents();
    }

    public String[] getRepositoryItems() {
        
        String[] repoList = null;
        
        try {
            RepositoryManager repo = new RepositoryManager();            
            ArrayList packageList = repo.getPackageList();
            repoList = (String[])packageList.toArray(new String[packageList.size()]);         
            
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(RepositoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return repoList;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        repoToolBar = new javax.swing.JToolBar(javax.swing.JToolBar.VERTICAL);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repository Manager", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP));
        setLayout(new java.awt.BorderLayout());

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = getRepositoryItems();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        repoToolBar.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gnome-Emblem-Downloads-32.png"))); // NOI18N
        jButton1.setToolTipText("Export");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        repoToolBar.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gnome-Edit-Delete-32.png"))); // NOI18N
        jButton2.setToolTipText("Delete");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        repoToolBar.add(jButton2);

        add(repoToolBar, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (jList1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Select a package to delete", "Delete Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int n = JOptionPane.showConfirmDialog(this, "Are you sure you want to permanently delete package '" + jList1.getSelectedValue().toString() + "'",
                    "Confirm delete", JOptionPane.YES_NO_OPTION);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar repoToolBar;
    // End of variables declaration//GEN-END:variables
}
